name: Build Xcode Project

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
        
  build:
    runs-on: self-hosted  # Use a macOS runner to build the Xcode project
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app  # Switch to Xcode 16.2

      - name: Build the Xcode project
        run: |
          /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project Morning.xcodeproj -scheme "Morning-Rem" -configuration Release clean build
          # Replace Morning.xcodeproj with your actual project file if needed
          
      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: .
